---
- name: Create user
  user:
    name: "{{ common_user }}"
    shell: /bin/bash
    groups: sudo
    append: true
    create_home: true
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Update apt packages
  apt:
    update_cache: true
    cache_valid_time: 86400
    upgrade: true

- name: Wait for dpkg lock to be released
  shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10 ; done;
  changed_when: false

- name: Update and install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_packages }}"
  register: apt_action
  retries: 10
  until: apt_action is success or ('/var/lib/dpkg/lock-frontend' not in apt_action.msg)

- name: Limit journalctl size
  lineinfile:
    path: "/etc/systemd/journald.conf"
    regexp: "^SystemMaxUse="
    line: "SystemMaxUse=100M"

