---
common_user: debian
common_timezone: "America/Chicago"
common_keyring_dir: "/etc/apt/keyrings"
common_packages:
  - sudo
  - curl
  - git
  - openssh-server
  - vim
  - make
  - gnupg
  - nfs-common
  - software-properties-common
  - jq
  - unzip
  - ca-certificates
  - qemu-guest-agent

common_nomad_version: "1.5.5-1"
common_consul_version: "1.15.2-1"
common_vault_version: "1.13.2-1"
common_consul_template_version: "0.31.0-1"
common_reset_nomad: true
