---
- hosts: all
  become: true
  vars:
    user: debian

  roles:
    - role: common
      vars:
        common_user: "{{ user }}"

    - name: Install Docker
      role: geerlingguy.docker
      vars:
        # install docker compose plugin instead of docker-compose binary
        - docker_install_compose_plugin: true
        - docker_install_compose: false
        - docker_users: ["{{ user }}"]

    - name: Goss validation
      role: kencx.ansible.goss
      vars:
        - goss_dir: "./goss"
        - goss_file: "base.yml"
