user:
  debian:
    exists: true
    groups:
      - debian
      - sudo
      - docker
    home: /home/debian

package:
  nfs-common:
    installed: true
  jq:
    installed: true
  unzip:
    installed: true

gossfile:
  docker.yml: {}
  security.yml: {}
